### ISSUE TITLE
Differences in bug check's name detection

### ISSUE THREAD

**Issue by LuigiBruno** [microsoftfeedback/WinDbg-Feedback#17] opened 2019-06-17 14:13 UTC
I've just analyzed a DMP file that recorded a 0x19C bugcheck: WinDbg version 10.0.10586.567 AMD64 didn't identify the bugcheck and reported the below output after executing **!analyze -v**

Unknown bugcheck code (19c)
Unknown bugcheck description
Arguments:
Arg1: 0000000000000050
Arg2: ffffb58f3dd24080

WinDbg Preview (Debugger client version: 1.0.1904.18001 - Debugger engine version: 10.0.18869.1002) did identify it and reported the below output after executing **!analyze -v**

WIN32K_POWER_WATCHDOG_TIMEOUT (19c)
Win32k did not turn the monitor on in a timely manner.
Arguments:
Arg1: 0000000000000050, Calling monitor driver to power on.
Arg2: ffffb58f3dd24080, Pointer to the power request worker thread.
Arg3: 0000000000000000
Arg4: 0000000000000000
Arg3: 0000000000000000
Arg4: 0000000000000000

Both the debuggers are running on Windows 10 Pro x64 (Version 1809 - OS Build 10.0.17763.557).

**Comment by aluhrs13** [comment] 2019-06-17 15:47
Can you clarify what the issue is? 10.0.10586 is over four years old so we've updated quite a bit since then. This looks to me like we've just added better analysis for this 0x19C bugchecks.

**Comment by LuigiBruno** [comment] 2019-06-18 13:45
> Can you clarify what the issue is? 10.0.10586 is over four years old so we've updated quite a bit since then. This looks to me like we've just added better analysis for this 0x19C bugchecks.

Thanks @aluhrs13.
I didn't install WinDbg as a standalone tool (maybe I've installed it as part of an old Visual Studio version, I cannot remember right now): where can I find a more recent version?

**Comment by rodwiddowson** [comment] 2019-06-18 13:58
It comes with the latest SDK (or is it) WDK.  You can choose to install just it IIRC

**Comment by aluhrs13** [comment] 2019-06-18 19:36
https://aka.ms/WinDbgDocs has the directions for installing the latest WinDbg. I'm going to close this out since it looks like an intentional change where the newer version has newer information.

**Closed by aluhrs13** 2019-06-18 19:36 UTC

**Comment by LuigiBruno** [comment] 2019-06-25 10:56
> It comes with the latest SDK (or is it) WDK.  You can choose to install just it IIRC

Thanks @rodwiddowson.

**Comment by LuigiBruno** [comment] 2019-06-25 10:57
> https://aka.ms/WinDbgDocs has the directions for installing the latest WinDbg. I'm going to close this out since it looks like an intentional change where the newer version has newer information.

Thanks @aluhrs13.
